name: "Publish every Git push to main to FlakeHub"
on:
  push:
    branches:
      - "main"
    paths:
      - "**/*.nix"
      - "flake.lock"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6
        with:
          persist-credentials: false
      - uses: "DeterminateSystems/determinate-nix-action@92ffb5400c3776307a27a1727d7e2ac3dcd9f844" # v3
      - uses: "DeterminateSystems/flakehub-push@e2ce584966282b479a2a6c43d5b313a46a33c25a" # main
        with:
          name: "adampie/opt-out"
          rolling: true
          visibility: "public"
          include-output-paths: true
